# Generated by Django 5.2.7 on 2025-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('vehicle_type', models.CharField(blank=True, choices=[('SINGLE MOTOR', 'SINGLE MOTOR'), ('TRICYCLE', 'TRICYCLE'), ('CAR', 'CAR'), ('TRUCK', 'TRUCK'), ('JEEP', 'JEEP')], max_length=50, null=True)),
                ('patient_type', models.CharField(blank=True, choices=[('DRIVER', 'DRIVER'), ('PASSENGER', 'PASSENGER'), ('PEDESTRIAN', 'PEDESTRIAN')], max_length=50, null=True)),
                ('vehicular_referred', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('vehicular_facility', models.CharField(blank=True, choices=[('SIARGAO ISLAND MEDICAL CENTER', 'SIARGAO ISLAND MEDICAL CENTER')], max_length=100, null=True)),
                ('vehicular_status', models.CharField(blank=True, choices=[('Recovered', 'Recovered'), ('Died', 'Died')], max_length=10, null=True)),
                ('injury_mechanism', models.CharField(blank=True, choices=[('FALLING', 'FALLING'), ('MAULING', 'MAULING'), ('STABBING', 'STABBING'), ('GUNSHOT', 'GUNSHOT'), ('EXPLOSION', 'EXPLOSION')], max_length=50, null=True)),
                ('injury_referred', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('injury_facility', models.CharField(blank=True, choices=[('SIARGAO ISLAND MEDICAL CENTER', 'SIARGAO ISLAND MEDICAL CENTER')], max_length=100, null=True)),
                ('injury_status', models.CharField(blank=True, choices=[('Recovered', 'Recovered'), ('Died', 'Died')], max_length=10, null=True)),
                ('suicide_mechanism', models.CharField(blank=True, choices=[('HANGING', 'HANGING'), ('POISONING', 'POISONING'), ('FIREARMS', 'FIREARMS'), ('SELF-IMMOLATION', 'SELF-IMMOLATION'), ('SUICIDE BY VEHICLE', 'SUICIDE BY VEHICLE')], max_length=50, null=True)),
                ('suicide_referred', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('suicide_facility', models.CharField(blank=True, choices=[('SIARGAO ISLAND MEDICAL CENTER', 'SIARGAO ISLAND MEDICAL CENTER')], max_length=100, null=True)),
                ('suicide_status', models.CharField(blank=True, choices=[('Recovered', 'Recovered'), ('Died', 'Died')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
