# Generated by Django 5.2.7 on 2025-10-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censusdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personrecord',
            old_name='created_at',
            new_name='date_recorded',
        ),
    ]
