# Generated by Django 5.2.7 on 2025-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censusdata', '0002_rename_created_at_personrecord_date_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrecord',
            name='injury_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personrecord',
            name='suicide_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personrecord',
            name='vehicular_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
