# Generated by Django 5.2.7 on 2025-11-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censusdata', '0003_personrecord_injury_no_personrecord_suicide_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personrecord',
            old_name='injury_facility',
            new_name='i_facility',
        ),
        migrations.RenameField(
            model_name='personrecord',
            old_name='injury_referred',
            new_name='i_referred',
        ),
        migrations.RenameField(
            model_name='personrecord',
            old_name='injury_status',
            new_name='i_status',
        ),
        migrations.RenameField(
            model_name='personrecord',
            old_name='suicide_facility',
            new_name='s_facility',
        ),
        migrations.RenameField(
            model_name='personrecord',
            old_name='suicide_referred',
            new_name='s_referred',
        ),
        migrations.RenameField(
            model_name='personrecord',
            old_name='suicide_status',
            new_name='s_status',
        ),
        migrations.RenameField(
            model_name='personrecord',
            old_name='vehicular_facility',
            new_name='v_facility',
        ),
        migrations.RenameField(
            model_name='personrecord',
            old_name='vehicular_referred',
            new_name='v_referred',
        ),
        migrations.RenameField(
            model_name='personrecord',
            old_name='vehicular_status',
            new_name='v_status',
        ),
        migrations.AddField(
            model_name='personrecord',
            name='i_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personrecord',
            name='s_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personrecord',
            name='v_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personrecord',
            name='injury_mechanism',
            field=models.CharField(blank=True, choices=[('FALLING', 'FALLING'), ('MAULING', 'MAULING'), ('STABBING', 'STABBING'), ('GUNSHOT', 'GUNSHOT'), ('EXPLOSION', 'EXPLOSION'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personrecord',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('DRIVER', 'DRIVER'), ('PASSENGER', 'PASSENGER'), ('PEDESTRIAN', 'PEDESTRIAN'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personrecord',
            name='suicide_mechanism',
            field=models.CharField(blank=True, choices=[('HANGING', 'HANGING'), ('POISONING', 'POISONING'), ('FIREARMS', 'FIREARMS'), ('SELF-IMMOLATION', 'SELF-IMMOLATION'), ('SUICIDE BY VEHICLE', 'SUICIDE BY VEHICLE'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personrecord',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('SINGLE MOTOR', 'SINGLE MOTOR'), ('TRICYCLE', 'TRICYCLE'), ('CAR', 'CAR'), ('TRUCK', 'TRUCK'), ('JEEP', 'JEEP'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
    ]
