# Generated by Django 5.2.7 on 2025-11-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censusdata', '0004_rename_injury_facility_personrecord_i_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrecord',
            name='p_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
